kind = "mobile"
previewPath = "/livreur/"
title = "Jatek Livreur"
version = "1.0.0"
id = "artifacts/livreur"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/livreur/" ]
localPort = 21054

[services.development]
run = "pnpm --filter @workspace/livreur run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/livreur", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/livreur", "run", "serve" ]

[services.env]
PORT = "21054"
BASE_PATH = "/livreur/"
